### ISSUE TITLE
[Bug]: Login: No identity model found

### ISSUE THREAD

**Issue by emiltsang-flow** [OneSignal/onesignal-vue#46]
### What happened?

"onesignal-vue": "^2.0.1"
OSModelStore.js:32 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'modelId')
at Ji.subscribeUpdateListener (OSModelStore.js:32:41)
at Ji.add (OSModelStore.js:16:14)
at en.add (CoreModuleDirector.js:106:32)
at tn. (LoginManager.js:113:9)
at Generator.next ()
at r (tslib.es6.js:118:58)

When I try to call the this.$OneSignal.login(EXTERNAL_ID), I got this error.

### What browsers are you seeing the problem on?

Chrome (Chromium)

### What operating system are you running?

macOS 14.1

### Steps to reproduce?

```Markdown
1. Install "onesignal-vue": "^2.0.1"
2. Run the app
3. invoke this.$OneSignal.login(EXTERNAL_ID)
4. console error Cannot read properties of undefined (reading 'modelId')
```

### What did you expect to happen?

Able to set the external id to one signal user

### Relevant log output

```Shell
OSModelStore.js:32 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'modelId')
    at Ji.subscribeUpdateListener (OSModelStore.js:32:41)
    at Ji.add (OSModelStore.js:16:14)
    at en.add (CoreModuleDirector.js:106:32)
    at tn.<anonymous> (LoginManager.js:113:9)
    at Generator.next (<anonymous>)
    at r (tslib.es6.js:118:58)
```

**Comment by fadi-george** [comment]
@emiltsang-flow Hello, are you still getting this error?
